### ISSUE TITLE
ignore-module vs external: function

### ISSUE THREAD

**Issue by stilva** [roman01la/react-native-babel#6]
Hi,

What are the benefits of using `ignore-module.js` as opposed to the following?

```javascript
externals: function(context, request, cb) {
  cb(null, context && context.indexOf('node_modules/react-native/') > -1);
}
```

Cheers

**Comment by jhabdas** [comment]
@stilva not sure if this helps at all, but I found that use of the [`dep-graph`](https://github.com/roman01la/react-native-babel/tree/dep-graph) branch provides a method to help minimize the size of the `ignore-modules.js` RegExp. However, I still [had to use](https://github.com/jhabdas/lumpen-radio/commit/2878e2474c2783a14e84d833bdbe36780f5c0781#diff-6d69fd424b731898c114e4c859b4fc5fR1) `ignore-modules.js` to allow me to leverage [Static Resources](https://facebook.github.io/react-native/docs/image.html#static-resources) in my app.

**Comment by stilva** [comment]
@jhabdas, thanks for the reply.
`externals` can be a RexExp (e.g. master branch of this repo) or a function that returns a Boolean.
By replacing `externals: [require('./ignore-modules')],` with
```javascript 
externals: function(context, request, cb) {
  cb(null, request.indexOf('image!') > -1 || context && context.indexOf('node_modules/react-native/') > -1);
},
```
you don't need `ignore-modules.js`, and it covers static images.

Moreover, React Native `0.6.0-rc` switched to `babel.js`, so all this might not be needed :smile:

**Comment by jhabdas** [comment]
Thanks for the info @stilva. After dropping the adjusted code snippet into [my Webpack config](https://github.com/jhabdas/lumpen-radio/blob/master/webpack.config.js) file and running the `webpack-watch` script I received the following error:

```
Unhandled rejection TypeError: undefined is not a function
    at /Users/jhabdas/Developer/lumpen-radio/webpack-watch.js:50:41
    at tryCatcher (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jhabdas/Developer/lumpen-radio/node_modules/react-native/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

YMMV. node v0.12.2

**Comment by roman01la** [comment]
Is it still relevant? We have Babel inside, why do you want to use this approach? 😅

**Comment by jhabdas** [comment]
@roman01la Could you help clarify what you mean by

> Is it still relevant?

Given this repo got my app off the ground and into the App Store I find it counterproductive to question the relevance of this project given it still works and eased development.

**Comment by jhabdas** [comment]
Ignore

**Comment by niftylettuce** [comment]
`image!foo.png` is not working

e.g.

`<Image source={require('image!foo.png')} />` is not working

**Comment by jhabdas** [comment]
Ahh, the early days.

**Comment by roman01la** [comment]
@niftylettuce I'm going to close this issue. Please, open another one and fill it with related info. If you know how to fix this, feel free to submit a PR. Thanks.
